from pathlib import Path
p=Path('/data/models/Kimi-K3/modeling_kimi_linear.py')
s=p.read_text()
if 'K3_EVENT_TIMING_V1' in s: raise SystemExit('already patched')
mark='import torch\n'
lines=['','# K3_EVENT_TIMING_V1','_K3_PENDING=[]; _K3_PARTS=[]','def _k3_ev():',' import os'," if not os.environ.get('K3_EVENT_TIMING'): return None",' e=torch.cuda.Event(enable_timing=True); e.record(); return e','def _k3_flush(a,b,tokens):',' import os,json',' if a is None: return',' _K3_PENDING.append((a,b,tokens))',' if len(_K3_PENDING)<16: return',' torch.cuda.synchronize(); rank=os.environ.get(\'RANK\',\'?\')',' for st,en,tok in _K3_PENDING:','  total=st.elapsed_time(en); attn=sum(x.elapsed_time(y) for n,x,y in _K3_PARTS if n==\'attention\'); moe=sum(x.elapsed_time(y) for n,x,y in _K3_PARTS if n==\'moe\')',"  print('K3_EVENT_TIMING_V1 '+json.dumps({'rank':rank,'tokens':int(tok),'model_ms':total,'attention_ms':attn,'moe_ms':moe,'other_ms':max(0.,total-attn-moe)},separators=(',',':')),flush=True)",' _K3_PENDING.clear(); _K3_PARTS.clear()','']
s=s.replace(mark,mark+'\n'.join(lines),1)
old='''        residual = hidden_states\n\n        hidden_states = self.input_layernorm(hidden_states)\n\n        # Self Attention\n'''; new='''        residual = hidden_states\n        _k3_as = _k3_ev()\n\n        hidden_states = self.input_layernorm(hidden_states)\n\n        # Self Attention\n'''; assert old in s; s=s.replace(old,new,1)
old='''        hidden_states = residual + hidden_states\n\n        # Fully Connected\n        residual = hidden_states\n        hidden_states = self.post_attention_layernorm(hidden_states)\n        if hasattr(self, "block_sparse_moe"):\n            hidden_states = self.block_sparse_moe(hidden_states)\n        else:\n            hidden_states = self.mlp(hidden_states)\n'''; new='''        hidden_states = residual + hidden_states\n        _k3_ae = _k3_ev() if _k3_as is not None else None\n\n        # Fully Connected\n        residual = hidden_states\n        hidden_states = self.post_attention_layernorm(hidden_states)\n        _k3_ms = _k3_ev() if _k3_as is not None else None\n        if hasattr(self, "block_sparse_moe"):\n            hidden_states = self.block_sparse_moe(hidden_states)\n        else:\n            hidden_states = self.mlp(hidden_states)\n        _k3_me = _k3_ev() if _k3_as is not None else None\n        if _k3_as is not None:\n            _K3_PARTS.append(("attention",_k3_as,_k3_ae)); _K3_PARTS.append(("moe",_k3_ms,_k3_me))\n'''; assert old in s; s=s.replace(old,new,1)
old='''        hidden_states = inputs_embeds\n        if past_key_values is not None:\n'''; new='''        hidden_states = inputs_embeds\n        _k3_model_start = _k3_ev()\n        if past_key_values is not None:\n'''; assert old in s; s=s.replace(old,new,1)
old='''        hidden_states = self.norm(hidden_states)\n\n        return BaseModelOutputWithPast(\n'''; new='''        hidden_states = self.norm(hidden_states)\n        _k3_model_end = _k3_ev() if _k3_model_start is not None else None\n        _k3_flush(_k3_model_start,_k3_model_end,inputs_embeds.shape[1])\n\n        return BaseModelOutputWithPast(\n'''; assert old in s; s=s.replace(old,new,1)
p.write_text(s); print('patched',p)
